위젯단위로 코드 분리
ifplant/ifplant_app pull request #33
Opened 2021-11-22 16:10 UTC by kimiszero

https://github.com/ifplant/ifplant_app/issues/31

2021-11-22 16:22 UTC, korca0220 requested changes
appBar 부분 또한 따로 컴포넌트 분리 부탁드립니다~
코드내 리뷰 확인 해주세요

2021-11-22 16:22 UTC, korca0220 commented on lib/app/ui/android/select_detail/select_plant_detail.dart
> +        ),
AppBar 부분은 따로 `appbar` 디렉토리 내에 분리해서 하면 다른 코드와 통일성 유지가 가능할 것 같습니다. ( 예시로 homeAppBar 는 따로 분리가 되어있습니다.
확인 부탁드립니다

2021-11-22 16:33 UTC, kimiszero commented on lib/app/ui/android/select_detail/select_plant_detail.dart
> +        ),
네 한번 더 수정해서 올리겠습니다!

2021-11-23 02:37 UTC, korca0220 approved these changes

2021-11-23 02:38 UTC, merged